#!/usr/bin/env bash
# D5 — Local Splunk harness teardown.
#
# Stops the container and (with -v) drops the named volumes so the
# next bootstrap.sh starts from a clean Splunk install. Also removes
# the harness-generated secrets.env so a subsequent
# `scripts/check-splunk-messages.sh` doesn't blindly hit a non-existent
# Splunk and emit a misleading network error.
#
# Usage:
#   bash docker/scripts/teardown.sh         # stop + drop volumes + clear secrets.env
#   bash docker/scripts/teardown.sh --keep-volumes  # stop only, preserve state

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOCKER_DIR="${REPO_ROOT}/docker"
SECRETS_FILE="${REPO_ROOT}/secrets.env"

KEEP_VOLUMES=0
for arg in "$@"; do
    case "$arg" in
        --keep-volumes) KEEP_VOLUMES=1 ;;
        -h|--help)
            sed -n '/^# /{s/^# //;p;}' "${BASH_SOURCE[0]}" | head -15
            exit 0
            ;;
        *)
            echo "[teardown] unknown arg: $arg" >&2
            exit 1
            ;;
    esac
done

if [ "$KEEP_VOLUMES" = "1" ]; then
    echo "[teardown] stopping container, preserving volumes ..."
    ( cd "$DOCKER_DIR" && docker compose stop )
else
    echo "[teardown] stopping container and dropping volumes ..."
    ( cd "$DOCKER_DIR" && docker compose down -v )
fi

# Only nuke secrets.env if it was generated by bootstrap.sh against
# the local harness. A maintainer may have hand-pointed secrets.env
# at a remote Splunk; preserve that.
if [ -f "$SECRETS_FILE" ] && grep -q '^SPLUNK_HOST=localhost$' "$SECRETS_FILE"; then
    rm -f "$SECRETS_FILE"
    echo "[teardown] removed ${SECRETS_FILE} (was pointing at local harness)"
elif [ -f "$SECRETS_FILE" ]; then
    echo "[teardown] preserved ${SECRETS_FILE} (SPLUNK_HOST != localhost — looks like a remote-tenant config)"
fi

# Clear the staging dir so a future bootstrap does not silently
# reinstall a stale tarball.
if [ -d "${DOCKER_DIR}/staging" ]; then
    find "${DOCKER_DIR}/staging" -mindepth 1 -delete 2>/dev/null || true
    echo "[teardown] cleared docker/staging/"
fi

echo "[teardown] DONE."
