[install]
is_configured = true
build = 5

[package]
id = esri_map_viz
check_for_updates = true

[ui]
is_visible = true
label = ESRI Web Map

[launcher]
author = Splunk Custom Viz
description = Interactive map visualization rendering ESRI web service layers with Leaflet and esri-leaflet
version = 3.1.0
